from pydantic import BaseModel, Field

from app.schemas.planner.task import Task


class ExecutionPlan(BaseModel):
    """
    Represents the complete execution plan
    generated by the planner.
    """

    goal: str = Field(
        ...,
        description="Original user goal."
    )

    tasks: list[Task] = Field(
        default_factory=list,
        description="Ordered list of tasks."
    )

    completed: bool = Field(
        default=False,
        description="Whether all tasks finished."
    )