from pydantic import BaseModel, Field

from app.schemas.planner.planner_task import PlannerTask


class PlannerResponse(BaseModel):
    """
    Complete response returned by the Planner LLM.
    """

    tasks: list[PlannerTask] = Field(
        default_factory=list,
        description="Ordered tasks generated by the planner."
    )