from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class TaskStatus(str, Enum):
    """
    Represents the current execution status of a task.
    """

    PENDING = "pending"
    READY = "ready"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"
    CANCELLED = "cancelled"


class Task(BaseModel):
    """
    Represents a single task generated by the planner.
    """

    id: int = Field(
        ...,
        description="Unique task number."
    )

    description: str = Field(
        ...,
        description="Human-readable description of the task."
    )

    tool_name: str = Field(
        ...,
        description="Tool that should execute this task."
    )

    arguments: dict[str, Any] = Field(
        default_factory=dict,
        description="Arguments required by the tool."
    )

    status: TaskStatus = Field(
        default=TaskStatus.PENDING,
        description="Current execution status."
    )

    result: Any | None = Field(
        default=None,
        description="Result produced after execution."
    )

    error: str | None = Field(
        default=None,
        description="Execution error if the task fails."
    )

    depends_on: list[int] = Field(
        default_factory=list,
        description="List of task IDs this task depends on."
    )

    priority: int = Field(
        default=1,
        description="Priority of the task (lower is higher priority)."
    )

    retry_count: int = Field(
        default=0,
        description="Number of times the task has been retried."
    )

    max_retries: int = Field(
        default=3,
        description="Maximum number of retries allowed."
    )

    started_at: float | None = Field(
        default=None,
        description="Timestamp when execution started."
    )

    finished_at: float | None = Field(
        default=None,
        description="Timestamp when execution finished."
    )

    execution_time: float | None = Field(
        default=None,
        description="Execution duration in seconds."
    )

    worker_id: int | None = Field(
        default=None,
        description="Identifier of the worker thread that executed the task."
    )

    failure_type: str | None = Field(
        default=None,
        description="Classification of execution failure: 'logical', 'infrastructure', or 'dependency'."
    )