import concurrent.futures
import threading
import time
from typing import Callable

from loguru import logger

from app.schemas.planner import (
    ExecutionPlan,
    Task,
    TaskStatus,
    ProgressEvent,
    ExecutionPolicy,
)

from app.registry.tool_executor import ToolExecutor


class ExecutionAgent:
    """
    Responsible for executing the tasks contained
    in an ExecutionPlan.
    """

    def __init__(self):

        self.tool_executor = ToolExecutor()
        self.lock = threading.Lock()
        self.on_progress = None
        self.stop_requested = False

    def execute(
        self,
        execution_plan: ExecutionPlan,
        on_progress: Callable[[ProgressEvent], None] = None,
        policy: ExecutionPolicy = ExecutionPolicy.FAIL_FAST,
    ) -> ExecutionPlan:
        """
        Execute tasks in the execution plan concurrently while respecting dependencies.

        Args:
            execution_plan:
                Plan generated by the Planner.
            on_progress:
                Callback function that receives ProgressEvent objects.
            policy:
                ExecutionPolicy determining behavior on task failures/empty results.

        Returns:
            Updated ExecutionPlan containing task results and execution status.
        """

        logger.info(
            f"Executing plan with {len(execution_plan.tasks)} task(s) "
            f"using policy={policy.value}."
        )

        self.on_progress = on_progress
        self.stop_requested = False

        # Reset non-terminal task statuses to PENDING for execution
        with self.lock:
            for task in execution_plan.tasks:
                if task.status not in (TaskStatus.COMPLETED, TaskStatus.EMPTY_RESULT, TaskStatus.FAILED):
                    task.status = TaskStatus.PENDING

        running_futures = {}

        with concurrent.futures.ThreadPoolExecutor(max_workers=10) as executor:
            while True:
                with self.lock:
                    # Under FAIL_FAST, stop scheduling new tasks if stop is requested
                    if self.stop_requested and policy == ExecutionPolicy.FAIL_FAST:
                        logger.info("Fail-fast triggered. Stopping execution scheduling.")
                        break

                    pending_tasks = [t for t in execution_plan.tasks if t.status == TaskStatus.PENDING]
                    running_tasks = [t for t in execution_plan.tasks if t.status == TaskStatus.RUNNING]

                    if not pending_tasks and not running_tasks:
                        break  # All tasks processed

                    # Resolve ready tasks
                    ready_tasks = []
                    for task in pending_tasks:
                        # Check if any parent dependencies failed
                        dep_failed = False
                        for dep_id in task.depends_on:
                            dep_task = next((t for t in execution_plan.tasks if t.id == dep_id), None)
                            if dep_task and dep_task.status == TaskStatus.FAILED:
                                dep_failed = True
                                break

                        if dep_failed:
                            task.status = TaskStatus.FAILED
                            task.error = "Parent dependency task failed."
                            self._emit_progress(task)
                            continue

                        # Check if all parent dependencies are completed/empty
                        deps_met = True
                        for dep_id in task.depends_on:
                            dep_task = next((t for t in execution_plan.tasks if t.id == dep_id), None)
                            if not dep_task or dep_task.status not in (TaskStatus.COMPLETED, TaskStatus.EMPTY_RESULT):
                                deps_met = False
                                break

                        if deps_met:
                            ready_tasks.append(task)

                    # Sort ready tasks by priority (lower number runs first)
                    ready_tasks.sort(key=lambda t: t.priority)

                    # Cycle Deadlock Detection
                    if pending_tasks and not running_tasks and not ready_tasks:
                        logger.error("Deadlock detected! Details:")
                        for pt in pending_tasks:
                            logger.error(f"  Pending: Task {pt.id} (description='{pt.description}', tool_name='{pt.tool_name}', depends_on={pt.depends_on})")
                        for pt in execution_plan.tasks:
                            if pt.status in (TaskStatus.COMPLETED, TaskStatus.EMPTY_RESULT):
                                logger.error(f"  Finished: Task {pt.id} (description='{pt.description}', tool_name='{pt.tool_name}', status={pt.status})")
                        raise ValueError(
                            "Deadlock detected: There are pending tasks but none are ready to execute "
                            "(likely due to a dependency cycle or missing parent task)."
                        )

                    # Launch ready tasks
                    for task in ready_tasks:
                        task.status = TaskStatus.RUNNING
                        task.started_at = time.time()
                        task.worker_id = len(running_futures) + 1
                        self._emit_progress(task)

                        future = executor.submit(self._run_task_wrapper, task)
                        running_futures[future] = task

                if not running_futures:
                    time.sleep(0.05)
                    continue

                # Wait for at least one thread future to complete
                done, _ = concurrent.futures.wait(
                    running_futures.keys(),
                    return_when=concurrent.futures.FIRST_COMPLETED
                )

                for future in done:
                    task = running_futures.pop(future)
                    try:
                        future.result()
                    except Exception as e:
                        logger.error(f"Task future raised unhandled error: {e}")

                    # Check if outcome should flag stop_requested
                    with self.lock:
                        if task.status == TaskStatus.FAILED:
                            self.stop_requested = True

        # Compute overall plan completeness status
        execution_plan.completed = all(
            task.status in (TaskStatus.COMPLETED, TaskStatus.EMPTY_RESULT)
            for task in execution_plan.tasks
        )

        logger.info("Execution finished.")
        return execution_plan

    def _run_task_wrapper(self, task: Task) -> None:
        """
        Runs a task's tool, checks for empty results,
        and logs execution metrics.
        """
        try:
            result = self.tool_executor.execute(
                tool_name=task.tool_name,
                arguments=task.arguments,
            )

            # Check if outcome is EMPTY_RESULT
            if self._is_empty_result(result):
                with self.lock:
                    task.status = TaskStatus.EMPTY_RESULT
                    task.result = result
                    task.finished_at = time.time()
                    task.execution_time = task.finished_at - task.started_at
                    task.error = None
                self._emit_progress(task)
            else:
                with self.lock:
                    task.status = TaskStatus.COMPLETED
                    task.result = result
                    task.finished_at = time.time()
                    task.execution_time = task.finished_at - task.started_at
                    task.error = None
                self._emit_progress(task)

        except Exception as error:
            with self.lock:
                task.status = TaskStatus.FAILED
                task.result = None
                task.finished_at = time.time()
                task.execution_time = task.finished_at - task.started_at
                task.error = str(error)
            self._emit_progress(task)

    def _is_empty_result(self, result) -> bool:
        """
        Determines if a task execution result is empty.
        """
        if result is None:
            return True
        if isinstance(result, (list, dict, set, str)) and not result:
            return True
        return False

    def _emit_progress(self, task: Task) -> None:
        """
        Helper to construct and emit ProgressEvent.
        """
        from datetime import datetime

        event = ProgressEvent(
            task_id=task.id,
            description=task.description,
            tool_name=task.tool_name,
            status=task.status,
            timestamp=datetime.utcnow(),
            execution_time=task.execution_time,
            worker_id=task.worker_id,
            retry_count=task.retry_count,
            error=task.error,
        )

        if self.on_progress:
            try:
                self.on_progress(event)
            except Exception as e:
                logger.error(f"Error in progress callback: {e}")
        else:
            status_str = task.status.value.upper()
            msg = f"[{status_str}] Task {task.id}: {task.description}"
            if task.execution_time is not None:
                msg += f" (took {task.execution_time:.2f}s)"
            if task.error:
                msg += f" - Error: {task.error}"
            print(msg, flush=True)