import concurrent.futures
import threading
import time
import random
from typing import Callable

import httpx
from loguru import logger

from app.schemas.planner import (
    ExecutionPlan,
    Task,
    TaskStatus,
    ProgressEvent,
    ExecutionPolicy,
)

from app.registry.tool_executor import ToolExecutor
from app.registry.llm_executor import LLMExecutor


class ExecutionAgent:
    """
    Responsible for executing the tasks contained
    in an ExecutionPlan.
    """

    def __init__(self):
        self.tool_executor = ToolExecutor()
        self.llm_executor = LLMExecutor()
        self.lock = threading.Lock()
        self.on_progress = None
        self.stop_requested = False
        self.worker_counter = 0

    def execute(
        self,
        execution_plan: ExecutionPlan,
        on_progress: Callable[[ProgressEvent], None] = None,
        policy: ExecutionPolicy = ExecutionPolicy.FAIL_FAST,
    ) -> ExecutionPlan:
        """
        Execute tasks in the execution plan concurrently while respecting dependencies.

        Args:
            execution_plan:
                Plan generated by the Planner.
            on_progress:
                Callback function that receives ProgressEvent objects.
            policy:
                ExecutionPolicy determining behavior on task failures/empty results.

        Returns:
            Updated ExecutionPlan containing task results and execution status.
        """

        logger.info(
            f"Executing plan with {len(execution_plan.tasks)} task(s) "
            f"using policy={policy.value}."
        )

        self.on_progress = on_progress
        self.stop_requested = False

        # Reset non-terminal task statuses to PENDING for execution, and reset worker counter
        with self.lock:
            self.worker_counter = 0
            for task in execution_plan.tasks:
                if task.status not in (TaskStatus.COMPLETED, TaskStatus.EMPTY_RESULT, TaskStatus.FAILED):
                    task.status = TaskStatus.PENDING

        # Pre-execution cycle detection to fail immediately if dependencies are cyclic
        self._detect_dependency_cycles(execution_plan.tasks)

        running_futures = {}

        with concurrent.futures.ThreadPoolExecutor(max_workers=10) as executor:
            while True:
                with self.lock:
                    # Under FAIL_FAST, stop scheduling new tasks if stop is requested
                    if self.stop_requested and policy == ExecutionPolicy.FAIL_FAST:
                        logger.info("Fail-fast triggered. Stopping execution scheduling.")
                        break

                    pending_tasks = [t for t in execution_plan.tasks if t.status == TaskStatus.PENDING]
                    running_tasks = [t for t in execution_plan.tasks if t.status == TaskStatus.RUNNING]

                    if not pending_tasks and not running_tasks:
                        break  # All tasks processed

                    # Resolve ready tasks
                    ready_tasks = []
                    for task in pending_tasks:
                        # Check if all parent dependencies are completed/empty
                        deps_met = True
                        for dep_id in task.depends_on:
                            dep_task = next((t for t in execution_plan.tasks if t.id == dep_id), None)
                            if not dep_task or dep_task.status not in (TaskStatus.COMPLETED, TaskStatus.EMPTY_RESULT):
                                deps_met = False
                                break

                        if deps_met:
                            ready_tasks.append(task)

                    # Sort ready tasks by priority (lower number runs first)
                    ready_tasks.sort(key=lambda t: t.priority)

                    # Cycle Deadlock Detection (fallback check)
                    if pending_tasks and not running_tasks and not ready_tasks:
                        logger.error("Deadlock detected! Details:")
                        for pt in pending_tasks:
                            logger.error(f"  Pending: Task {pt.id} (description='{pt.description}', tool_name='{pt.tool_name}', depends_on={pt.depends_on})")
                        for pt in execution_plan.tasks:
                            if pt.status in (TaskStatus.COMPLETED, TaskStatus.EMPTY_RESULT):
                                logger.error(f"  Finished: Task {pt.id} (description='{pt.description}', tool_name='{pt.tool_name}', status={pt.status})")
                        raise ValueError(
                            "Deadlock detected: There are pending tasks but none are ready to execute "
                            "(likely due to a dependency cycle or missing parent task)."
                        )

                    # Launch ready tasks
                    for task in ready_tasks:
                        task.status = TaskStatus.RUNNING
                        task.started_at = time.time()
                        self.worker_counter += 1
                        task.worker_id = self.worker_counter
                        self._emit_progress(task)

                        future = executor.submit(self._run_task_wrapper, task, execution_plan)
                        running_futures[future] = task

                if not running_futures:
                    time.sleep(0.05)
                    continue

                # Wait for at least one thread future to complete
                done, _ = concurrent.futures.wait(
                    running_futures.keys(),
                    return_when=concurrent.futures.FIRST_COMPLETED
                )

                for future in done:
                    task = running_futures.pop(future)
                    try:
                        future.result()
                    except Exception as e:
                        logger.error(f"Task future raised unhandled error: {e}")

                    # Check if outcome should flag stop_requested
                    with self.lock:
                        if task.status == TaskStatus.FAILED:
                            self.stop_requested = True

        # Compute overall plan completeness status
        execution_plan.completed = all(
            task.status in (TaskStatus.COMPLETED, TaskStatus.EMPTY_RESULT)
            for task in execution_plan.tasks
        )

        logger.info("Execution finished.")
        return execution_plan

    def _run_task_wrapper(self, task: Task, execution_plan: ExecutionPlan) -> None:
        """
        Runs a task's tool, checks for empty results,
        and logs execution metrics with transient failure retries.
        """
        from app.registry.tool_registry import AVAILABLE_TOOLS

        max_retries = task.max_retries
        retry_delay = 1.0

        for attempt in range(max_retries + 1):
            try:
                # Check if it should be executed via API ToolExecutor or LLMExecutor fallback
                if task.tool_name in AVAILABLE_TOOLS and AVAILABLE_TOOLS[task.tool_name] is not None:
                    result = self.tool_executor.execute(
                        tool_name=task.tool_name,
                        arguments=task.arguments,
                    )
                else:
                    result = self.llm_executor.execute(
                        description=task.description,
                        arguments=task.arguments,
                    )

                # Check if outcome is EMPTY_RESULT
                if self._is_empty_result(result):
                    with self.lock:
                        task.status = TaskStatus.EMPTY_RESULT
                        task.result = result
                        task.finished_at = time.time()
                        task.execution_time = task.finished_at - task.started_at
                        task.error = None
                    self._emit_progress(task)
                else:
                    with self.lock:
                        task.status = TaskStatus.COMPLETED
                        task.result = result
                        task.finished_at = time.time()
                        task.execution_time = task.finished_at - task.started_at
                        task.error = None
                    self._emit_progress(task)
                return

            except Exception as error:
                is_retryable = False

                # Trace back to the root cause in case exceptions are wrapped by service classes
                root_err = error
                while root_err.__cause__ is not None:
                    root_err = root_err.__cause__

                # Identify if the root exception is transient and retryable
                if isinstance(root_err, httpx.RequestError):
                    is_retryable = True
                elif isinstance(root_err, httpx.HTTPStatusError):
                    status_code = root_err.response.status_code
                    if status_code == 429 or status_code >= 500:
                        is_retryable = True

                if is_retryable and attempt < max_retries:
                    task.retry_count = attempt + 1
                    sleep_time = retry_delay * (2 ** attempt) + random.uniform(0.1, 0.5)
                    logger.warning(
                        f"Task {task.id} transient failure ({error}). "
                        f"Retrying in {sleep_time:.2f}s (Attempt {task.retry_count}/{max_retries})..."
                    )
                    time.sleep(sleep_time)
                else:
                    # Final failure - propagate recursively to all downstream tasks
                    with self.lock:
                        task.status = TaskStatus.FAILED
                        task.result = None
                        task.finished_at = time.time()
                        task.execution_time = task.finished_at - task.started_at
                        task.error = str(error)
                        self._propagate_failure(execution_plan, task.id)
                    self._emit_progress(task)
                    return

    def _propagate_failure(self, execution_plan: ExecutionPlan, failed_task_id: int) -> None:
        """
        Recursively fail all downstream tasks that depend on the failed task.
        """
        for task in execution_plan.tasks:
            if task.status == TaskStatus.PENDING and failed_task_id in task.depends_on:
                task.status = TaskStatus.FAILED
                task.error = f"Parent dependency task {failed_task_id} failed."
                self._emit_progress(task)
                self._propagate_failure(execution_plan, task.id)

    def _detect_dependency_cycles(self, tasks: list[Task]) -> None:
        """
        Detect if there is any dependency cycle in the tasks.
        Raises ValueError if a cycle is detected.
        """
        adj = {t.id: t.depends_on for t in tasks}
        visited = {}  # id -> state (0 = visiting, 1 = visited)

        def dfs(node_id):
            if node_id in visited:
                if visited[node_id] == 0:
                    raise ValueError(f"Dependency cycle detected involving task {node_id}")
                return

            visited[node_id] = 0
            for dep in adj.get(node_id, []):
                dfs(dep)
            visited[node_id] = 1

        for t in tasks:
            dfs(t.id)

    def _is_empty_result(self, result) -> bool:
        """
        Determines if a task execution result is empty.
        """
        if result is None:
            return True
        if isinstance(result, (list, dict, set, str)) and not result:
            return True
        return False

    def _emit_progress(self, task: Task) -> None:
        """
        Helper to construct and emit ProgressEvent.
        """
        from datetime import datetime

        event = ProgressEvent(
            task_id=task.id,
            description=task.description,
            tool_name=task.tool_name,
            status=task.status,
            timestamp=datetime.utcnow(),
            execution_time=task.execution_time,
            worker_id=task.worker_id,
            retry_count=task.retry_count,
            error=task.error,
        )

        if self.on_progress:
            try:
                self.on_progress(event)
            except Exception as e:
                logger.error(f"Error in progress callback: {e}")
        else:
            status_str = task.status.value.upper()
            msg = f"[{status_str}] Task {task.id}: {task.description}"
            if task.execution_time is not None:
                msg += f" (took {task.execution_time:.2f}s)"
            if task.error:
                msg += f" - Error: {task.error}"
            print(msg, flush=True)